### ISSUE TITLE
Getting Elastic 8.x to GA

### ISSUE THREAD

**Issue by ruflin** [ruflin/Elastica#2185]
Lots of work has been over the past year to make Elastica compatible with Elasticsearch 8.x. Also many discussions have happened. This issue is to track the missing bits to make it GA and also have a single place to link together all discussions and PRs.

## TODO

* [x] PR to get Elastica 8 to alpha: https://github.com/ruflin/Elastica/pull/2181
* [x] Follow up on dependency lib version needed: https://github.com/ruflin/Elastica/pull/2181#issuecomment-1826405139 https://github.com/ruflin/Elastica/pull/2186
* [x] Update README files with 8.x notes
* [x] Update changelog with breaking changes
* [x] Add migration guide from 7.x to 8.x https://github.com/ruflin/Elastica/pull/2214
* [x] https://github.com/ruflin/Elastica/pull/2188

## Links

* [Discussions around Elastica 8.0](https://github.com/ruflin/Elastica/discussions/1961)
* [Initial 8 PR that kicked of the work](https://github.com/ruflin/Elastica/pull/2168)

**Comment by pawelkeska** [comment]
@ruflin please reopen, not all tasks were completed

**Comment by ruflin** [comment]
Argh, this was closed automatically. Thanks for the ping.

**Comment by ruflin** [comment]
I just pushed a 8.0.0-alpha1 tag as a release to get more testing on these changes: https://github.com/ruflin/Elastica/tree/8.0.0-alpha1

**Comment by ruflin** [comment]
@sidz I wonder if it is time to push out 8.0 GA? We have not really had any feedback since the alpha release. So either there are no problems or nobody migrates :-) Would be great if some folks that migrated (or failed to migrate) could chime in with a 👍 or 👎

**Comment by sidz** [comment]
I think we are good to go @ruflin and release 8.0 so we will start getting feedback. I guess FOSElasticaBundle wait Elastica release :)

Also, probably I will try to upgrade one of my project I'm working with to the 8.0 in the nearest future.

**Comment by limenet** [comment]
@ruflin @sidz we've been using in conjunction with https://github.com/valantic/pimcore-elastica-bridge successfully in production in multiple productions for quite some time now, so definitely a 👍🏽

**Comment by mussbach** [comment]
Indeed it would be much easier for me to test if FOSElasticaBundle would be updated as well. I would migrate quite soon to 8 and can provide feedback (although we only use a small subset of the features).

**Comment by ruflin** [comment]
I just opened https://github.com/ruflin/Elastica/pull/2215 to prepare for the 8.0.0 release. As soon as this PR is in, I plan to tag a release. Please everyone have a quick look to see if I miss anything.

**Comment by ruflin** [comment]
Release 8.0.0 is out: https://github.com/ruflin/Elastica/releases/tag/8.0.0 Thanks to everyone that made it possible. Special callout to @sidz and @pawelkeska for your massive code contributions and keep pushing as forward, @thePanz and @deguif for all the guidance and everyone that kept chiming in with bugs, help, comments, PRs etc. It took a village to release to get 8.0.0 out of the door.
